name: CI - El Buen Sabor Mobile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: 拘勇 Checkout del c칩digo
      uses: actions/checkout@v3

    - name: 游냕 Instalar Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: 游닍 Instalar dependencias
      run: flutter pub get

    - name: 游댌 An치lisis Est치tico (Quality Gate)
      # Esto detecta errores de c칩digo aunque no tengas tests
      run: flutter analyze

    - name: 游님 Verificar Compilaci칩n (Smoke Test)
      # Si esto pasa, significa que la app "funciona" a nivel estructural
      run: flutter build apk --debug --no-pub